syntax = "proto3";

option csharp_namespace = "Shared.Grpc.Trip";

package trip;

service TripGrpc {
  rpc GetByVehicle (VehicleIdRequest) returns (TripListReply);
  rpc Create (CreateTripRequest) returns (TripReply);
}

message VehicleIdRequest {
  string vehicle_id = 1;
}

message CreateTripRequest {
  string vehicle_id = 1;
  string start_time = 2;
  string end_time = 3;
  double distance_km = 4;
  double average_speed = 5;
  optional double fuel_consumed = 6;
  optional double energy_consumed = 7;
  optional string start_location_id = 8;
  optional string end_location_id = 9;
}

message TripReply {
  string id = 1;
  string vehicle_id = 2;
  string start_time = 3;
  string end_time = 4;
  double distance_km = 5;
  double average_speed = 6;
  optional double fuel_consumed = 7;
  optional double energy_consumed = 8;
  optional string start_location_id = 9;
  optional string end_location_id = 10;
}

message TripListReply {
  repeated TripReply trips = 1;
}
