<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Alert.API</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Alert.Application\Alert.Application.csproj" />
        <ProjectReference Include="..\Alert.Infrastructure\Alert.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="NSwag.AspNetCore" Version="14.6.3" />
    </ItemGroup>

</Project>